ALARM_SOUNDS: bool = False

HIGH_TEMP_C: float = 80
HIGH_HUMIDITY_PERCENT: float = 60
TEMPERATURE_RESOLVE_THRESHOLD: float = 30
HUMIDITY_RESOLVE_THRESHOLD: float = 55.0

NTFY_URL: str = "https://notifs.charlesmills.tech/qvllncV7GhPceiwa"
NOTIFICATION_COOLDOWN: int = 30
NOTIFICATION_GLOBAL_COOLDOWN: int = 1